// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3W6nkla0esafmztWRwCrZS2pPgXJ-fdQ',
    appId: '1:594555605322:android:2c2d3a9cb791ef6b73f1b3',
    messagingSenderId: '594555605322',
    projectId: 'jobsareusplatform',
    storageBucket: 'jobsareusplatform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQQtmmTqAsa0uxtKam-4CjVNhdzsNyNYk',
    appId: '1:594555605322:ios:00f33e3b6ef2065c73f1b3',
    messagingSenderId: '594555605322',
    projectId: 'jobsareusplatform',
    storageBucket: 'jobsareusplatform.appspot.com',
    iosBundleId: 'com.example.employerLowonganKita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ9KnMx3J9aSNUYToIvnFuixuOq3pvt9k',
    appId: '1:816122565473:web:e89f331fe7d01b956bab20',
    messagingSenderId: '816122565473',
    projectId: 'roomies-e7601',
    authDomain: 'roomies-e7601.firebaseapp.com',
    databaseURL: 'https://roomies-e7601-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roomies-e7601.appspot.com',
    measurementId: 'G-F0GGGV0E4R',
  );

}